### ISSUE TITLE
[NEW FEATURE] 播放器置顶取消和端口优化

### ISSUE THREAD

**Issue by MisakaSakura** [xfangfang/Macast#25]
## New feature
1. 播放器置顶开关
2. 开机自启选项
~~3. 倍速播放功能支持~~
4. 提供简单的内置使用说明
## Additional context
1）我发现不是play版b站不能投屏，而是不能投缓存的视频，只能投在线的视频
2）取消播放器置顶真的挺重要的了，因为切其他应用的时候它也一直置顶得手动把它最小化，有点影响使用
3）搜不到的情况多数时候可能是端口被占用，能否优化一下呢？还有如果实在暂时没有改善方法或许加个开机启动能暂时变向解决？
4）我发现投送的视频
i. 在b站因为被整个屏蔽掉了播放器页面，所以无法在手机端进行视频倍速播放![Screenshot_20210825-135753.png](https://user-images.githubusercontent.com/30547550/130736532-b235d853-3f2b-484d-866b-3b59404430ca.png)
ii. bubbleUPnP播放也不支持视频倍速播放
~~iii. 投屏的MPV客户端也没有视频倍速播放功能~~
iv. 最好能提供投屏播放器MPV的快捷键说明，因为没有设置UI，很多人更常用的播放器可能是potplayer这类，导致误以为投屏播放器缺失大部分功能就像我原先以为的第三点一样（毕竟面向用户不可能全是技术出身，还是希望能尽可能用户友好些）

**Comment by xfangfang** [comment]
非常棒的反馈，都是很需要的功能，可以等待后续逐步更新

**Comment by xfangfang** [comment]
可以在 https://github.com/xfangfang/Macast/actions 下载最新的测试版，针对端口问题进行了优化，在有端口冲突时会自动使用新的端口。也可以在配置文件中对端口号进行指定。

配置文件位置
```yaml
macOS: ~/Library/Application\ Support/Macast
linux: ~/.config/Macast
windows: %HOMEPATH%\AppData\Local\xfangfang\Macast
```
